"""
Agricultural AI Flask Application
==================================
Web interface for crop yield prediction and scenario analysis.
Uses pooled anomaly models (France + UK) from the cross-country transfer research.
"""

from flask import Flask, render_template, request, jsonify
import pandas as pd
import numpy as np
import joblib
import os
import json

from utils.risk_analyzer import RiskAnalyzer

app = Flask(__name__)

# Load configuration
CROPS = ['Wheat', 'Winter_Barley', 'Spring_Barley', 'Oats', 'OSR']
REGIONS = ['England', 'Wales', 'Scotland', 'Northern Ireland']

# Load crop-specific model config (generated by train_pooled_models.py)
MODEL_CONFIG = {}
_config_path = os.path.join(os.path.dirname(__file__), 'models', 'model_config.json')
if os.path.exists(_config_path):
    with open(_config_path) as f:
        MODEL_CONFIG = json.load(f)

# Legacy weather ranges for risk page (which uses its own heuristic scoring)
WEATHER_RANGES = {
    'Summer_Rain': {'min': 100, 'max': 400, 'default': 200, 'unit': 'mm'},
    'Summer_Sun': {'min': 400, 'max': 700, 'default': 550, 'unit': 'hours'},
    'Winter_Frost': {'min': 10, 'max': 50, 'default': 25, 'unit': 'days'},
    'Spring_Rain': {'min': 100, 'max': 300, 'default': 175, 'unit': 'mm'},
    'Spring_Frost': {'min': 0, 'max': 20, 'default': 8, 'unit': 'days'},
    'Summer_Tmax': {'min': 18, 'max': 26, 'default': 21, 'unit': '°C'},
    'Grain_Filling_Rain': {'min': 50, 'max': 250, 'default': 150, 'unit': 'mm'},
    'Grain_Filling_Sun': {'min': 200, 'max': 500, 'default': 350, 'unit': 'hours'},
}

# Pre-load models, scalers, and metadata
_models = {}
_scalers = {}
_meta = {}
_models_dir = os.path.join(os.path.dirname(__file__), 'models')
for crop_name in CROPS:
    model_file = os.path.join(_models_dir, f'{crop_name.lower()}_model.pkl')
    scaler_file = os.path.join(_models_dir, f'{crop_name.lower()}_scaler.pkl')
    meta_file = os.path.join(_models_dir, f'{crop_name.lower()}_meta.pkl')
    if os.path.exists(model_file) and os.path.exists(scaler_file):
        _models[crop_name] = joblib.load(model_file)
        _scalers[crop_name] = joblib.load(scaler_file)
    if os.path.exists(meta_file):
        _meta[crop_name] = joblib.load(meta_file)


@app.route('/')
def index():
    """Main page with prediction form."""
    # Pass initial features for the default crop (Wheat)
    default_crop = 'Wheat'
    initial_features = MODEL_CONFIG.get(default_crop, {})
    return render_template('index.html',
                           crops=CROPS,
                           regions=REGIONS,
                           model_config=MODEL_CONFIG,
                           initial_crop=default_crop,
                           initial_features=initial_features)


@app.route('/api/features/<crop>')
def get_crop_features(crop):
    """Return feature configuration for a specific crop."""
    if crop not in MODEL_CONFIG:
        return jsonify({'success': False, 'error': f'Unknown crop: {crop}'}), 404
    return jsonify({'success': True, **MODEL_CONFIG[crop]})


@app.route('/predict', methods=['POST'])
def predict():
    """Make yield prediction based on weather inputs."""
    try:
        data = request.get_json()
        crop = data.get('crop', 'Wheat')
        region = data.get('region', 'England')

        crop_config = MODEL_CONFIG.get(crop, {})
        model_type = crop_config.get('model_type', 'Unknown')

        if crop in _models and crop in _scalers and crop in _meta:
            # Pooled anomaly prediction flow:
            # 1. Convert user's raw weather values to z-scores
            # 2. Build full feature vector (0 for non-specified features)
            # 3. Scale and predict yield anomaly
            # 4. Add UK base yield
            prediction = predict_pooled_anomaly(crop, region, data)
        elif crop in _models and crop in _scalers:
            # Legacy model (no meta file): direct feature scaling
            feature_names = list(crop_config.get('features', {}).keys())
            features = []
            for feat in feature_names:
                default_val = crop_config['features'][feat].get('default', 0)
                features.append(float(data.get(feat, default_val)))
            features_array = np.array([features])
            features_scaled = _scalers[crop].transform(features_array)
            prediction = _models[crop].predict(features_scaled)[0]
        else:
            prediction = calculate_fallback_prediction(crop, data)

        confidence = calculate_confidence(data)
        extremes = detect_extreme_conditions(data)
        historical_avg = get_historical_average(crop)

        return jsonify({
            'success': True,
            'prediction': round(float(prediction), 2),
            'confidence': confidence,
            'unit': 't/ha',
            'crop': crop,
            'region': region,
            'model_type': model_type,
            'historical_avg': historical_avg,
            'deviation': round(float(prediction) - historical_avg, 2),
            'extreme_conditions': extremes
        })

    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})


def predict_pooled_anomaly(crop, region, data):
    """
    Pooled anomaly prediction: convert raw weather to z-scores,
    predict yield anomaly, add UK base yield.

    The model was trained on detrended yield anomalies with weather z-scores.
    For prediction:
      - Convert user-provided raw weather values to z-scores using
        saved UK regional statistics (mean, std per feature)
      - Non-specified features default to z-score 0 (average conditions)
      - Predict the yield anomaly
      - Add UK base yield to get final prediction
    """
    meta = _meta[crop]
    model = _models[crop]
    scaler = _scalers[crop]

    model_features = meta['model_features']
    uk_stats = meta['uk_weather_stats']
    base_yield = meta['uk_base_yield']

    # Use region-specific stats if available, otherwise overall UK stats
    region_stats = uk_stats.get(region, uk_stats.get('_overall', {}))

    # Build z-score feature vector
    z_scores = []
    for feat in model_features:
        raw_value = data.get(feat)
        feat_stats = region_stats.get(feat, uk_stats.get('_overall', {}).get(feat))

        if raw_value is not None and feat_stats is not None:
            # User provided this feature — convert to z-score
            mean = feat_stats['mean']
            std = feat_stats['std']
            if std > 0.001:
                z = (float(raw_value) - mean) / std
            else:
                z = 0.0
            z_scores.append(z)
        else:
            # Feature not provided — assume average conditions (z=0)
            z_scores.append(0.0)

    # Scale z-scores using the training-fitted StandardScaler and predict
    z_array = np.array([z_scores])
    z_scaled = scaler.transform(z_array)
    predicted_anomaly = model.predict(z_scaled)[0]

    # Final yield = base yield + weather anomaly effect
    prediction = base_yield + predicted_anomaly

    return prediction


def calculate_fallback_prediction(crop, data):
    """Simple rule-based prediction when model not available."""
    base_yields = {
        'Wheat': 8.0,
        'Winter_Barley': 6.5,
        'Spring_Barley': 5.5,
        'Oats': 5.8,
        'OSR': 3.2
    }

    base = base_yields.get(crop, 7.0)
    adjustment = 0.0

    # Use whatever weather features are available in the request
    summer_rain = float(data.get('Summer_Rain', data.get('summer_rain', 200)))
    summer_sun = float(data.get('Summer_Sun', data.get('summer_sun', 550)))
    winter_frost = float(data.get('Winter_Frost', data.get('winter_frost', 25)))
    spring_rain = float(data.get('Spring_Rain', data.get('spring_rain', 175)))
    summer_tmax = float(data.get('Summer_Tmax', data.get('summer_tmax', 21)))

    rain_diff = abs(summer_rain - 200)
    adjustment -= (rain_diff / 100) * 0.4

    sun_diff = summer_sun - 550
    if sun_diff > 0:
        adjustment += min(sun_diff / 120, 0.4)
    else:
        adjustment += (sun_diff / 130) * 0.5

    frost_excess = max(0, winter_frost - 20)
    adjustment -= (frost_excess / 30) * 0.5

    spring_rain_diff = abs(spring_rain - 175)
    adjustment -= (spring_rain_diff / 125) * 0.3

    if summer_tmax > 22:
        adjustment -= ((summer_tmax - 22) / 4) * 0.6
    elif summer_tmax < 19:
        adjustment -= ((19 - summer_tmax) / 3) * 0.3

    prediction = base + adjustment
    return round(max(prediction, 2.0), 2)


def calculate_confidence(data):
    """Calculate prediction confidence based on weather extremity."""
    extreme_count = 0

    # Check various weather features if they exist in the input
    summer_rain = float(data.get('Summer_Rain', data.get('summer_rain', 200)))
    winter_frost = float(data.get('Winter_Frost', data.get('winter_frost', 25)))
    spring_rain = float(data.get('Spring_Rain', data.get('spring_rain', 175)))
    summer_sun = float(data.get('Summer_Sun', data.get('summer_sun', 550)))

    if summer_rain > 350 or summer_rain < 120:
        extreme_count += 1
    if winter_frost > 45:
        extreme_count += 1
    if spring_rain > 280 or spring_rain < 100:
        extreme_count += 1
    if summer_sun < 350:
        extreme_count += 1

    if extreme_count == 0:
        return 'High'
    elif extreme_count <= 2:
        return 'Medium'
    else:
        return 'Low'


def detect_extreme_conditions(data):
    """Detect which weather conditions are extreme and provide recommendations."""
    extremes = []

    summer_rain = float(data.get('Summer_Rain', data.get('summer_rain', 200)))
    winter_frost = float(data.get('Winter_Frost', data.get('winter_frost', 25)))
    spring_rain = float(data.get('Spring_Rain', data.get('spring_rain', 175)))
    grain_filling_rain = float(data.get('Grain_Filling_Rain', data.get('grain_filling_rain', 150)))

    if grain_filling_rain > 300:
        extremes.append({
            'condition': 'High Grain Filling Rain',
            'impact': 'Negative',
            'description': 'Excess rain during grain filling reduces quality and yield',
            'recommendation': 'Monitor crops for disease. Consider preventive fungicide. Check field drainage.'
        })
    if summer_rain > 320:
        extremes.append({
            'condition': 'High Summer Rain',
            'impact': 'Negative',
            'description': 'Excess rain during growth period',
            'recommendation': 'Monitor for lodging and disease. Check drainage.'
        })
    if winter_frost > 40:
        extremes.append({
            'condition': 'Severe Winter',
            'impact': 'Negative',
            'description': 'Frost damage to overwintering crops',
            'recommendation': 'Assess crop damage in early spring. Consider reseeding if necessary.'
        })
    if spring_rain > 350:
        extremes.append({
            'condition': 'Wet Spring',
            'impact': 'Negative',
            'description': 'Waterlogging delays planting and establishment',
            'recommendation': 'Delay planting until conditions improve. Ensure good drainage.'
        })

    return extremes


def get_historical_average(crop):
    """Get historical average yield for crop."""
    averages = {
        'Wheat': 8.0,
        'Winter_Barley': 6.5,
        'Spring_Barley': 5.5,
        'Oats': 5.8,
        'OSR': 3.2
    }
    return averages.get(crop, 6.5)


@app.route('/scenario')
def scenario():
    """Scenario analysis page with interactive sliders."""
    return render_template('scenario.html',
                           crops=CROPS,
                           model_config=MODEL_CONFIG)


@app.route('/risk')
def risk():
    """Risk assessment dashboard page."""
    return render_template('risk.html',
                           crops=CROPS,
                           regions=REGIONS,
                           weather_ranges=WEATHER_RANGES)


@app.route('/api/risk', methods=['POST'])
def calculate_risk():
    """API endpoint for risk assessment calculation."""
    try:
        data = request.get_json()
        crop = data.get('crop', 'Wheat')
        region = data.get('region', 'England')
        hectares = float(data.get('hectares', 100))
        years_ahead = int(data.get('years_ahead', 10))

        # Get weather inputs (accept both old 8-feature and new crop-specific)
        weather = {
            'Summer_Rain': float(data.get('Summer_Rain', 200)),
            'Summer_Sun': float(data.get('Summer_Sun', 550)),
            'Winter_Frost': float(data.get('Winter_Frost', 25)),
            'Spring_Rain': float(data.get('Spring_Rain', 175)),
            'Spring_Frost': float(data.get('Spring_Frost', 8)),
            'Summer_Tmax': float(data.get('Summer_Tmax', 21)),
            'Grain_Filling_Rain': float(data.get('Grain_Filling_Rain', 150)),
            'Grain_Filling_Sun': float(data.get('Grain_Filling_Sun', 350)),
        }

        analyzer = RiskAnalyzer()

        risk_assessment = analyzer.calculate_risk_score(weather, crop)
        climate_projection = analyzer.project_climate_impact(crop, years_ahead)
        financial_risk = analyzer.calculate_financial_risk(crop, region, weather, hectares)
        historical_trend = analyzer.get_historical_risk_trend(crop)

        return jsonify({
            'success': True,
            'risk_assessment': risk_assessment,
            'climate_projection': climate_projection,
            'financial_risk': financial_risk,
            'historical_trend': historical_trend
        })

    except Exception as e:
        return jsonify({'success': False, 'error': str(e)})


if __name__ == '__main__':
    print("Starting Agricultural AI Flask Application...")
    print(f"Loaded model config for crops: {list(MODEL_CONFIG.keys())}")
    print(f"Loaded models: {list(_models.keys())}")
    print("Open http://localhost:5000 in your browser")
    app.run(debug=True, port=5000)
